### ISSUE TITLE
Lyrics stop working

### ISSUE THREAD

**Issue by hsl1** [Natoune/SpotifyMobileLyricsAPI#5]
Hi,

This lyrics on this music works last week but not now, appea
ring like this this week
Is there any fix needed? 
![Screenshot_20240929_132939_Spotify](https://github.com/user-attachments/assets/eeddcf4d-d3da-4fbc-bf0c-77a0727bdbae)
Nice project hope for a fix.
Lyrics stop working on all musics 🙃

**Comment by Natoune** [comment]
It seems that the Spotify app is having issues (https://downdetector.com/status/spotify/). It's probably related to this. I wish I could check but I can't log into my Spotify account so I don't know. I think it's best to just wait for Spotify to fix the problem.

**Comment by hsl1** [comment]
yes spotify has having some problems like 1 hour ago but now is working fine for me.
this error start happend like 3 days ago

**Comment by Rairof** [comment]
Seems like this is not an issue with spotify being down. I have quite a few reports of users having this issue of no lyric being present even after the spotify status has been restored. Its best to look into it to check if there really is some sort of connecting time out or other issue that happens when fetching lyrics of songs
Here are few things the users reported that I found interesting- 
![image](https://github.com/user-attachments/assets/7ef07ce7-1fb3-400b-b373-7d45d9b971dd)
Issue pics-
![image](https://github.com/user-attachments/assets/21f01629-d808-40c0-bd48-a2080b38717d)
![image](https://github.com/user-attachments/assets/a20c43ac-71c7-409c-8f1d-597897f41ffc)

**Comment by Natoune** [comment]
For my part, I really can't connect to the Spotify mobile application, so it's complicated to check if there are problems with the lyrics. However I had tried after the last commit about 8 hours ago (when I could still connect), and everything worked perfectly.

I directly use the Spotify Api, maybe the Spotify servers block certain requests because they are too numerous, I don't know.
When I look in the server's logs, everything seems to work.

![Vercel logs](https://github.com/user-attachments/assets/f5017fa0-d0f8-458b-81d5-070b82d05360)

I will have to invest in this problem but for the moment I am blocked because I no longer have access to the app...

**Comment by AshesToAshes76** [comment]
Hello! Just adding on to this :)

I just downloaded the Spotify Lite version from your releases and installed it on my device. All song lyrics seem to not load.


![Screenshot_20240929_152702_Spotify Lite](https://github.com/user-attachments/assets/3b2f36c9-92fb-4ec2-9c6b-4d76f5adbde1)

**Comment by Natoune** [comment]
> Hello! Just adding on to this :)
> 
> I just downloaded the Spotify Lite version from your releases and installed it on my device. All song lyrics seem to not load.
> 
> Let me know if there is anything I can do to help and I hope this only requires a quick fix; this project is AWESOME :D

I admit that I have not tested my patch on the Lite version of Spotify 😅
I think I know where the problem comes from, I will try to fix it and let you know when it is ok. (i have to sleep now, but it should be fine tomorrow)

**Comment by Natoune** [comment]
> Seems like this is not an issue with spotify being down. I have quite a few reports of users having this issue of no lyric being present even after the spotify status has been restored. Its best to look into it to check if there really is some sort of connecting time out or other issue that happens when fetching lyrics of songs Here are few things the users reported that I found interesting-

Regarding this issue, I was finally able to log in, but everything works perfectly for me.
If this issue appears randomly, it will be difficult to fix, but I will do my best.

**Comment by AshesToAshes76** [comment]
No worries! I was just testing Spotify Lite to see if that one was working (I generally use the regular version of Spotify). Thanks for your hard work :)

**Comment by hsl1** [comment]
Hi,
I dont know where the problem is but thanks for your time to see this.
Lite version not working also!

**Comment by Natoune** [comment]
Spotify Lite is now working !
You can patch it with the latest `patch_xmanager.sh` or download it from the [releases section](https://github.com/Natoune/SpotifyMobileLyricsAPI/releases/latest).

**Comment by AshesToAshes76** [comment]
Awesome, I will test and return here shortly with an update. Thank you for your hard work :)

**Comment by hsl1** [comment]
thanks but will be available for stock version?

**Comment by Natoune** [comment]
> thanks but will be available for stock version?

Do you mean that the lyrics still don't work for you on the stock version?

**Comment by hsl1** [comment]
I have downloaded from the link and it's working now.
What i mean is just because you just speak about the lite version.
Sometimes the letter comes first than the music but maybe it's their fault

**Comment by Natoune** [comment]
> I have downloaded from the link and it's working now.

I added an option to keep the Spotify API token in memory on the server. This significantly reduces the number of requests to Spotify's servers. This may be what fixed the issue.

>  Sometimes the letter comes first than the music but maybe it's their fault

Yes I think it is the MusixMatch API that produces this.

**Comment by AshesToAshes76** [comment]
Update: It seems like the most recent patch worked wonders! I installed the most up-to-date version and I haven't encounted lyrics not loading! Amazing work @Natoune and I look forward to seeing your other projects :D
